---
# k8s deployment with two replicas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-deploy
  labels:
    app: buildit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: buildit
  template:
    metadata:
      labels:
        app: buildit
    spec:
      containers:
      - name: buildit
      # Docker image is built using circleci whenever there is a change
        image: navala/building-on-ci:latest
        ports:
        - containerPort: 3000
---
  # k8s service to expose the deployment using Load balancer which uses round-robin strategy
  # Service can be accessed using curl://<LoadBalancerIP> (external IP)
  # Eg: curl http://34.105.25.206
apiVersion: v1
kind: Service
metadata:
  name: buildit-service
spec:
  type: LoadBalancer
  selector:
    app: buildit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
