---
version: 2
jobs:
  test:
    docker:
    - image: cimg/node:13.11.0
    steps:
    - checkout
    - run:
        command: |
          if [ ! -f "package.json" ]; then
            echo
            echo "---"
            echo "Unable to find your package.json file. Did you forget to set the app-dir parameter?"
            echo "---"
            echo
            echo "Current directory: $(pwd)"
            echo
            echo
            echo "List directory: "
            echo
            ls
            exit 1
          fi
        name: Checking for package.json.
        working_directory: ~/project
    - run:
        command: npm run test
        name: Run NPM Tests
        working_directory: ~/project
  build:
    environment:
      IMAGE_NAME: navala/building-on-ci
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
            echo "Published the docker image to Dockerhub"
workflows:
  version: 2
  node-tests:
    jobs:
    - test:
        filters:
          branches:
            only:
            - feature/devops
            - master
    - build:
        requires:
        - test
        filters:
          branches:
            only: master
